name: Build and Push Docker Image (manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (default: latest)"
        required: false
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: meta
        run: |
          TAG=${{ github.event.inputs.image_tag }}
          if [ -z "$TAG" ]; then TAG=latest; fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            nasir17/korean-tour-app-crawler:${{ steps.meta.outputs.tag }}
          platforms: linux/amd64


